spring:
  datasource:
    #mysql的连接信息
    url: jdbc:mysql://192.168.1.3:3306/chatLite?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone = GMT&allowPublicKeyRetrieval=true
    #用户名
    username: root
    #密码
    password: qqa222888
#  是否打开swagger文档 生产环境关闭
enable:
  swagger: true

