spring:
  datasource:
    #mysql的连接信息
    url: jdbc:mysql://43.143.247.151:3306/blog?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone = GMT
    #用户名
    username: chatlite
    #密码
    password: qqa222888
#  是否打开swagger文档 生产环境关闭
enable:
  swagger: false

